# Generated by Django 4.2.7 on 2026-03-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_education_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
